ground_segmentation:
  ros__parameters:
    n_threads: 4                # number of threads to use. 使用的线程数

    r_min: 0.2                  # minimum point distance. 距离最小值
    r_max: 50.0                 # maximum point distance. 距离最大值
    n_bins: 120                 # number of radial bins. 径向分割数
    n_segments: 360             # number of radial segments. 角向分割数

    max_dist_to_line: 0.05      # maximum vertical distance of point to line to be considered ground. 点到线的最大垂直距离

    sensor_height: 0.65         # sensor height above ground. 传感器高度
    min_slope: 0.0              # minimum slope of a ground line. 最小斜率
    max_slope: 0.3              # maximum slope of a ground line. 最大斜率
    max_fit_error: 0.05         # maximum error of a point during line fit. 最大拟合误差
    long_threshold: 1.0         # distance between points after which they are considered far from each other. 
    max_long_height: 0.1        # maximum height change to previous point in long line.
    max_start_height: 0.2       # maximum difference to estimated ground height to start a new line.
    line_search_angle: 0.1      # how far to search in angular direction to find a line [rad].

    gravity_aligned_frame: ""   # Frame which has its z axis aligned with gravity. (Sensor frame if empty.)

    visualize: false            # visualize segmentation result - USE ONLY FOR DEBUGGING

    input_topic: "livox/lidar_PointCloud2"
    obstacle_output_topic: "segmentation/obstacle"
    ground_output_topic: "segmentation/ground"